name: mm_utils
description: "MeetMighty Utils"
version: 2.2.1
repository: https://github.com/appmeetmighty/mm_utils
issue_tracker: https://github.com/appmeetmighty/mm_utils/issues

environment:
  sdk: ^3.6.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  encrypt: ^5.0.3
  crypto: ^3.0.6
  http: ^1.3.0
  intl: ^0.20.2
  internet_connection_checker: ^3.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
